### ISSUE TITLE
Update rules do not work as expected

### ISSUE THREAD

**Issue by fisherab** [icatproject/icat.server#127]
```
Apparently, create permissions are checked for the item that would
have created by the action.  But update permissions are only checked
for the item as it is before the action.  It is not checked whether
the user has update permission to the item as it would be after the
update action.

It is is not good enough to just check after the update - otherwise you could steal
other people's datasets and move them into your investigation. One possibility would
be to check against the UPDATE permissions before the change and against the CREATE
permissions after the change. I think this would give the expected semantics.
```

Original issue reported on code.google.com by `dr.s.m.fisher` on 2014-11-18 10:05:59

**Comment by fisherab** [comment]
I would like to get this one fixed. Considering again the case where an update is applied to a dataset which causes it to move from one investigation to another where it may have different authz rules applying to it including acquiring the ability to DELETE I can think of four solutions:

1. Just check that the user has UPDATE access before the change (the current state of the code). In this case we must just accept that offering UPDATE privileges is potentially dangerous.

1. Check for UPDATE permissions before the change and CREATE permissions after the change. This prevents somebody indirectly creating something that they could not create directly.

1. Check for UPDATE permissions before and CREATE permissions afterwards and check that if DELETE was not allowed before the change it is not allowed after the change. This may be enough but it would mean that you might lose your UPDATE privileges after the change and so could not reverse the process with another UPDATE.

1. Check for UPDATE permissions before and CREATE permissions afterwards and check that the update causes no authorization (C, R, U or D) to change. Or equivalently check for UPDATE and CREATE permissions before and check that the update causes no authorization (C, R, U or D) to change. This does require a number of database accesses to achieve but it does seem very safe.

Comments please. My preference is for solution 4 though it is the most expensive

**Comment by tomgriffinstfc** [comment]
Query on 4: " check that the update causes no authorization (C, R, U or D) to change."
Is this just from the perspective of the current user or all users?

For example, by moving the dataset to an investigation where the PI of the new investigation has Delete permissions a user could allow the deletion of a dataset that by someone else, which could be used as a workaround for this check.

I would favour (2) as it covers the important case.

If you allow Update then the user could pretty well wipe a record of its information content without Deleting it, so Update permissions should be given out carefully.........maybe a case for per-attribute permissions....

**Comment by fisherab** [comment]
I had only considered the user making the change and not the impact for other users which as Tom points out makes even solution 4 incomplete.

I have already coded solution 2 but not checked it in yet because of the earlier discussion with Rolf.

I agree that permissions on individual attributes might help, but I hope we don't need to go there.

I will join Tom in the "2" camp.

Steve

**Comment by kevinphippsstfc** [comment]
Having spoken to Steve, I agree that 2 is a sensible way forward. I think that option 4, even though it might seem the most comprehensive, is not really what you would want anyway. You have to accept that when you move something, it is likely to be inheriting permissions from its new parent entities and therefore the CRUD permissions on it effectively change.

**Comment by fisherab** [comment]
I have currently coded 2 but am leaving this open in case Rolf, who originally reported this does not agree.

**Comment by RKrahl** [comment]
In order to know whether update rules work as expected, we need to discuss our reasonable expectations first.  This is not obvious, expectations tend to vary a lot according to the particular case and context.

At least, it is certainly reasonable to expect that create permission is needed in order to create an object and delete permission in order to delete an object.  Things become complicated as the conditions for the rules may be formulated in terms of related objects.  For instance, it is common to grant access permissions on datasets and datafiles depending on the investigation these objects are related to.

Let's consider examples:

Example case 1 (create by update): assume a user has read permission to an Investigation A, but not create permission to datasets within this investigation.  But he got create and update permission to datasets in another Investigation B.  With ICAT 4.6.1, the user can still create a dataset in Investigation A like this:

```python
>>> dataset = client.new("dataset")
>>> dataset.name = "bummer"
>>> dataset.complete = False
>>> dataset.type = dstype
>>> dataset.investigation = invb
>>> dataset.create()
>>> dataset.investigation = inva
>>> dataset.update()
```

So this contradicts the expectation formulated above.

Example case 2 (delete by update): assume a user has read and update, but not delete permission to datasets in Investigation A.  But he got delete permission to datasets in another Investigation B.  The user can still delete a dataset in Investigation A like this:

```python
>>> dataset = client.search("Dataset INCLUDE 1 [name='bummer' AND investigation.id=%d]" % inva.id)[0]
>>> dataset.investigation = invb
>>> dataset.update()
>>> client.delete(dataset)
```

Again, this contradicts the expectation formulated above.

Example case 3 (update an attribute): I would expect that changing an attribute field on an object should only require update permission.  E.g. the following should be allowed for a user having read and update, but not create or delete permission on the dataset:

```python
>>> dataset = client.search("Dataset INCLUDE 1 [name='bummer']")[0]
>>> dataset.complete = True
>>> dataset.update()
```

Note that I have the extra condition "complete = False" in the update rule for Dataset in my ICAT.  As soon as a dataset is marked complete, it becomes read-only.  So, the update of the dataset in this example actually revokes update permission and cannot be reversed by the user.  This is exactly what I intend with this rule and I would like this to continue to work this way.

Example case 4 (update a relation): there are some object relations in the ICAT schema that I would consider more like an attribute.  One example is datafileFormat in Datafile.  So I would expect updating datafileFormat in a datafile to work the same way as updating an attribute field.


So what is different with examples 1 & 2?  Why is only checking update permission not enough here?  We tend to take a hierarchical view on the objects in the ICAT, with Investigation <- Dataset <- Datafile.  We speak of the datasets within an investigation and the datafiles within a dataset.  That is why it makes sense to formulate the conditions in access rules for datasets and datafiles based on the investigation they are related with.  From this point of view, updating the investigation relation in a dataset is more like moving the dataset to another location rather then changing the dataset itself.  Or, if we take the analogy of a file system, it's more like moving a file (which requires write permission to the involved directories) rather then modifying the file's content (which requires write permission on the file itself).


Now let's check Steve's suggested solutions against these examples:

Solution 1 would contradict expectations for examples 1 & 2.  Examples 3 & 4 would work as expected.

Solution 2 would fix example 1 but not example 2.  It would break all use cases where one would like to grant update but not create permission.  And it would break use cases where the update implicitly revokes write permissions on the object as described in the note to example 3.

Solution 3 would fix examples 1 & 3, but would otherwise cause the same problems as solution 2.  Furthermore it would still allow to move a dataset from one investigation to another one without DELETE permission, provided that the user has also not DELETE permission on datasets in the other investigation.

Solution 4 is rather safe, but still has loopholes as Tom pointed out and would still allow moving datasets out of an investigation without DELETE permission in some cases.  It would also break use cases where an implicit change of permissions by the update is intended as described in the note to example 3.


I'm not quite happy with either solution.  I'd like to suggest a different one:

Check UPDATE permission before the change in any case.  If the update modifies any not nullable many to one relationship (cardinality 1,1 in the schema), check additionally DELETE permission before and CREATE permission after the change.

This would work as expected in all the examples.

**Comment by fisherab** [comment]
I now almost agree with Rolf's proposal. I think however that rather than just checking on non-nullable many to one relationships we should check on relationships that are part of the key. In most cases this is the same but it is clearer. For example a Dataset (indentified by Investigation and name) has non-nullable many to one relationships to both Investigation and to DatasetType. Changing the DatasetType does not change the primary key so UPDATE permission is all that is required.  So my suggestion is:

Check UPDATE permission before the change.  If the update modifies any relationship field that is part of the primary key also check DELETE permission before and CREATE permission after the change.

**Comment by RKrahl** [comment]
Just to avoid any ambiguity, I assume you mean by "primary key" the uniqueness constraint in the schema.

Yes, indeed, that was also an option that I considered and I am happy with it.  In fact, I was mostly indecisive whether I should propose "non-nullable" or "uniqueness constraint" as the criterion.  In any case, the difference between the two options is minor.

**Comment by fisherab** [comment]
Yes I do mean the uniqueness constraint in the schema.

Steve
