### ISSUE TITLE
ORDER BY causes duplicate results

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/icat.server#154]
Reported as a bug in TopCAT, but is really an ICAT issue. https://github.com/icatproject/topcat/issues/130

```
>>> query = "SELECT inv FROM Investigation inv, inv.facility f, inv.investigationInstruments invinvestigationInstruments WHERE (f.id = 155) AND (UPPER(inv.name) LIKE '%88888888-XX%') ORDER BY invinvestigationInstruments.instrument.fullName ASC INCLUDE inv.investigationInstruments.instrument LIMIT 0, 50"
>>> result = client.search(query)
>>> len(result)
3
>>> result[0] == result[1]
True
>>> result[1] == result[2]
True
>>> 
>>> query2 = "SELECT DISTINCT inv FROM Investigation inv, inv.facility f, inv.investigationInstruments invinvestigationInstruments WHERE (f.id = 155) AND (UPPER(inv.name) LIKE '%88888888-XX%') ORDER BY invinvestigationInstruments.instrument.fullName ASC INCLUDE inv.investigationInstruments.instrument LIMIT 0, 50"
>>> result2 = client.search(query)
>>> result2 == result
True
```

**Comment by RKrahl** [comment]
I would say, this is independent of using DISTINCT in the query or not.  The bug is obviously related to ordering by a one to many relation:

```python
>>> query1 = "SELECT inv FROM Investigation inv, inv.facility f, inv.investigationInstruments invinvestigationInstruments WHERE (f.id = 155) AND (UPPER(inv.name) LIKE '%15202703-EF%') ORDER BY invinvestigationInstruments.instrument.fullName ASC"
>>> result1 = client.search(query1)
>>> len(result1)
3
>>> query2 = "SELECT inv FROM Investigation inv, inv.facility f, inv.investigationInstruments invinvestigationInstruments WHERE (f.id = 155) AND (UPPER(inv.name) LIKE '%15202703-EF%')"
>>> result2 = client.search(query2)
>>> len(result2)
1
>>> query3 = "SELECT inv FROM Investigation inv, inv.facility f, inv.investigationInstruments invinvestigationInstruments WHERE (f.id = 155) AND (UPPER(inv.name) LIKE '%15202703-EF%') ORDER BY inv.name ASC"
>>> result3 = client.search(query3)
>>> len(result3)
1
```

Here, query1 orders by a one to many relation, query2 has no ordering at all, and query3 orders by a simple attribute.  But I would say, the number of result should always be independent of the ORDER BY clause, regardless if using DISTINCT or not.

**Comment by fisherab** [comment]
So far I have been unable to reproduce this. My code is:

	Investigation invA = session.createInvestigation(facility, "A", "Not null", investigationType);

	Investigation invB = session.createInvestigation(facility, "B", "Not null", investigationType);

	Investigation invC = session.createInvestigation(facility, "C", "Not null", investigationType);

	Instrument wish = session.createInstrument(facility, "WISH");
	Instrument bone = session.createInstrument(facility, "BONE");

	session.createInvestigationInstrument(invA, wish);
	session.createInvestigationInstrument(invA, bone);
	session.createInvestigationInstrument(invB, wish);

assertEquals(1,
				session.search(
						"SELECT inv FROM Investigation inv, inv.facility f, inv.investigationInstruments ii WHERE inv.name ='A' ORDER BY ii.instrument.fullName ASC")
						.size());

**Comment by RKrahl** [comment]
I can confirm that following your test procedure, I get the same result as you.

However, I can still reproduce the bug.  I boiled it down to a pretty minimal example.  The bug reproduces as follows:

1. Start with an empty ICAT.
2. Import the content from [issue-154.icat](https://github.com/icatproject/icat.server/files/44907/issue-154.icat.txt) into the ICAT.
3. Run the following in a Python client:

```Python
>>> facility = client.assertedSearch("Facility")[0]
>>> name = 'inv A'
>>> query = ("SELECT inv FROM Investigation inv, inv.facility f, "
...          "inv.investigationInstruments invinvestigationInstruments "
...          "WHERE (f.id = %d) AND (UPPER(inv.name) LIKE '%%%s%%') "
...          "ORDER BY invinvestigationInstruments.instrument.fullName ASC "
...          "INCLUDE inv.investigationInstruments.instrument LIMIT 0, 50" 
...          % (facility.id, name.upper()))
>>> res = client.search(query)
>>> print("count: %d" % len(res))
count: 3
>>> print("names: %s" % ", ".join([inv.name for inv in res]))
names: inv A, inv A, inv A
```

I believe, the relevant difference to your test is that you did not set the Instrument.fullNames.

**Comment by fisherab** [comment]
Thanks for this small example - that should allow me to track the problem
down.

Steve

**Comment by fisherab** [comment]
I have now added this test (translated into java) and can confirm the behaviour described by Rolf.

**Comment by fisherab** [comment]
This is another bug in eclipselink. The JQPL I generate is: 

    SELECT DISTINCT $0$ FROM Investigation $0$ , $0$.facility $1$, 
    $0$.investigationInstruments $2$ 
    WHERE  ( $1$.id = 25548 ) AND ( UPPER ( $0$.name ) LIKE '%%INV A%%' )
    ORDER BY $2$.instrument.fullName ASC

This is converted for MySQL to: 

    SELECT DISTINCT t1.ID AS a1, t1.CREATE_ID AS a2, t1.CREATE_TIME AS a3, t1.DOI AS a4,
    t1.ENDDATE AS a5, t1.MOD_ID AS a6, t1.MOD_TIME AS a7, t1.NAME AS a8, 
    t1.RELEASEDATE AS a9, t1.STARTDATE AS a10, t1.SUMMARY AS a11, t1.TITLE AS a12,
    t1.VISIT_ID AS a13, t1.FACILITY_ID AS a14, t1.TYPE_ID AS a15, t3.FULLNAME AS a16 FROM
    INSTRUMENT t3, INVESTIGATIONINSTRUMENT t2, INVESTIGATION t1, FACILITY t0 WHERE
    (((t1.FACILITY_ID = 257) AND UPPER(t1.NAME) LIKE '%%INV A%%') AND (((t0.ID =
    t1.FACILITY_ID) AND (t2.INVESTIGATION_ID = t1.ID)) AND (t3.ID = t2.INSTRUMENT_ID))) 
    ORDER BY t3.FULLNAME ASC

and for Oracle to:

    SELECT DISTINCT t1.ID AS a1, t1.CREATE_ID AS a2, t1.CREATE_TIME AS a3, t1.DOI AS a4,
    t1.ENDDATE AS a5, t1.MOD_ID AS a6, t1.MOD_TIME AS a7, t1.NAME AS a8, t1.RELEASEDATE
    AS a9, t1.STARTDATE AS a10, t1.SUMMARY AS a11, t1.TITLE AS a12, t1.VISIT_ID AS a13,
    t1.FACILITY_ID AS a14, t1.TYPE_ID AS a15, t3.FULLNAME AS a16 FROM INSTRUMENT t3,
    INVESTIGATIONINSTRUMENT t2, INVESTIGATION t1, FACILITY t0 WHERE (((t1.FACILITY_ID
    = 25548) AND UPPER(t1.NAME) LIKE '%%INV A%%') AND (((t0.ID = t1.FACILITY_ID) AND
    (t2.INVESTIGATION_ID = t1.ID)) AND (t3.ID = t2.INSTRUMENT_ID)))
    ORDER BY t3.FULLNAME ASC;
 
I have tried with the latest eclipselink (2.6.1) on WildFly and the problem remains. I don't see a practical work around. The problem is that the generated SQL includes the instrument name is the list of fields that should be distinct. This is triggered by the "ORDER BY" on that field. If I hack the generated SQL and remove the field from the DISTINCT list it works as we would hope for MySQL but Oracle just throws an error. The error seems reasonable as what does it mean to order by something that is not visible? Perhaps the original JPQL might also be considered to be faulty.

Before I take the issue to the eclipselink community I would appreciate people's thoughts.

Steve

**Comment by fisherab** [comment]
Thinking about this some more - I now consider that the problem is that the original query is invalid as the query is trying to order investigations by the name of the related instrument - however this is a many to many relationship. I tried changing the ORDER BY of the query to: ORDER BY inv.facility.name ASC. This results in the following SQL (for MySQL):

    SELECT DISTINCT t1.ID AS a1, t1.CREATE_ID AS a2, t1.CREATE_TIME AS a3, t1.DOI AS a4,
    t1.ENDDATE AS a5, t1.MOD_ID AS a6, t1.MOD_TIME AS a7, t1.NAME AS a8, t1.RELEASEDATE
    AS a9, t1.STARTDATE AS a10, t1.SUMMARY AS a11, t1.TITLE AS a12, t1.VISIT_ID AS a13,
    t1.FACILITY_ID AS a14, t1.TYPE_ID AS a15, t0.NAME AS a16 FROM FACILITY t0, 
    INVESTIGATIONINSTRUMENT t2, INVESTIGATION t1 WHERE (((t1.FACILITY_ID = ?) AND
    UPPER(t1.NAME) LIKE ?) AND ((t0.ID = t1.FACILITY_ID) AND (t2.INVESTIGATION_ID = t1.ID))) 
    ORDER BY t0.NAME ASC LIMIT ?, ?

where this time I have not substitituted the "?" binding variables. The order by field is still included in the DISTINCT list but as exactly one facility can be associated with an investigation there is no problem.

I am now convinced that this is a bug in Eclipselink. I do not propose to provide a workaround.

**Comment by fisherab** [comment]
Reported as https://bugs.eclipse.org/bugs/show_bug.cgi?id=483657

**Comment by RKrahl** [comment]
I tend to agree not to fix this.  To be honest, I was somewhat surprised that icat.server allows ordering by a one to many relationships at all.  The Query class in python-icat (the JPQL query builder) refuses adding one to many relationships to ORDER BY clauses, because it is not quite clear what this order is supposed to be.

However, I still think that the number of results from a search should be independent of any ORDER BY clause.  Maybe one should explicitly disable this.  That is, throwing a ParameterError if any one to many relationships appears in ORDER BY rather then returning a possibly defective result.
